# permissions for end users to edit ondemandbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ondemandbackup-editor-role
rules:
- apiGroups:
  - database.dhoover103.com
  resources:
  - ondemandbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.dhoover103.com
  resources:
  - ondemandbackups/status
  verbs:
  - get
