---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
      - services
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for database.dhoover103.com/v1alpha1, Kind: MongoDB
  ##
  - apiGroups:
      - database.dhoover103.com
    resources:
      - mongodbs
      - mongodbs/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - '*'
  ##
  ## Rules for database.dhoover103.com/v1alpha1, Kind: Restore
  ##
  - apiGroups:
      - database.dhoover103.com
    resources:
      - restores
      - restores/status
      - restores/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for database.dhoover103.com/v1alpha1, Kind: OnDemandBackup
  ##
  - apiGroups:
      - database.dhoover103.com
    resources:
      - ondemandbackups
      - ondemandbackups/status
      - ondemandbackups/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
# +kubebuilder:scaffold:rules
