# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/database.dhoover103.com_mongodbs.yaml
- bases/database.dhoover103.com_restores.yaml
- bases/database.dhoover103.com_ondemandbackups.yaml
# +kubebuilder:scaffold:crdkustomizeresource
